[build]
  command = "npm run functions"
  publish = "public"
  functions = "functions"

[dev]
  publish = "public"
  functions = "functions"

[template.environment]
  STRIPE_PUBLISHABLE_KEY = "pk_test_51IOTaABKXqx5PFiXSNqyYxUvdvc4BZWPTvAkOeObOCBrmQg3Dlg9Jm3pHMqm8fL009QFUgowGMeXpNLQLCqVAyAP008KQgIjzK"
  STRIPE_SECRET_KEY = "sk_test_51IOTaABKXqx5PFiXwDnc7UIZs44910kloW77LW9dlJfNa4OzcM4sVVG4qGlyiwiHl7CJWnVnqPaBtO1OVqbA06s500iuJ37Rs3"
  STRIPE_WEBHOOK_SECRET= "whsec_QhH2qV1MS4eFTMNJC1r94tpa01FbdJVE"